AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    Simple implementation of a REST API for an imaginary todo app.

Globals:
  Function:
    Runtime: nodejs8.10
    Timeout: 60
    Tags:
      stage:
        Ref: StageName

Parameters:
  S3BucketName:
    Type: String
    Description: The name of the S3 bucket in which the Swagger specification can be found.
  StageName:
    Type: String
    Default: dev
    Description: The Lambda Function Stage

Resources:

  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name:
        Fn::Sub: todo-app-api-${StageName}
      StageName: dev
      DefinitionBody:
          Fn::Transform:
            Name: AWS::Include
            Parameters:
              Location:
                Fn::Join:
                  - ''
                  - - 's3://'
                    - Ref: S3BucketName
                    - '/swagger.yaml'

  ListTasksFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: todo-app-${StageName}-list-tasks
      CodeUri: src/
      Handler: index.listTasks
      Policies:
        DynamoDBReadPolicy:
          TableName:
            Ref: TasksTable
      Environment:
        Variables:
          TABLE_NAME:
            Ref: TasksTable

  # Permisson must be granted to API Gateway for invoking a Lambda function
  # (https://github.com/awslabs/serverless-application-model/issues/59)
  ListTasksFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: ListTasksFunction
      Principal: apigateway.amazonaws.com

  CreateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: todo-app-${StageName}-create-task
      CodeUri: src/
      Handler: index.createTask
      Policies:
        DynamoDBCrudPolicy:
          TableName:
            Ref: TasksTable
      Environment:
        Variables:
          TABLE_NAME:
            Ref: TasksTable

  # Permisson must be granted to API Gateway for invoking a Lambda function
  # (https://github.com/awslabs/serverless-application-model/issues/59)
  CreateTaskFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: CreateTaskFunction
      Principal: apigateway.amazonaws.com

  GetTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: todo-app-${StageName}-get-task
      CodeUri: src/
      Handler: index.getTask
      Policies:
        DynamoDBReadPolicy:
          TableName:
            Ref: TasksTable
      Environment:
        Variables:
          TABLE_NAME:
            Ref: TasksTable

  # Permisson must be granted to API Gateway for invoking a Lambda function
  # (https://github.com/awslabs/serverless-application-model/issues/59)
  GetTaskFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: GetTaskFunction
      Principal: apigateway.amazonaws.com

  UpdateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: todo-app-${StageName}-update-task
      CodeUri: src/
      Handler: index.updateTask
      Policies:
        DynamoDBCrudPolicy:
          TableName:
            Ref: TasksTable
      Environment:
        Variables:
          TABLE_NAME:
            Ref: TasksTable

  # Permisson must be granted to API Gateway for invoking a Lambda function
  # (https://github.com/awslabs/serverless-application-model/issues/59)
  UpdateTaskFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: UpdateTaskFunction
      Principal: apigateway.amazonaws.com

  DeleteTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: todo-app-${StageName}-delete-task
      CodeUri: src/
      Handler: index.deleteTask
      Policies:
        DynamoDBCrudPolicy:
          TableName:
            Ref: TasksTable
      Environment:
        Variables:
          TABLE_NAME:
            Ref: TasksTable

  # Permisson must be granted to API Gateway for invoking a Lambda function
  # (https://github.com/awslabs/serverless-application-model/issues/59)
  DeleteTaskFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: DeleteTaskFunction
      Principal: apigateway.amazonaws.com

  TasksTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName:
        Fn::Sub: todo-app-${StageName}-tasks
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      Tags:
        stage:
          Ref: StageName

Outputs:
  ApiUrl:
    Value:
      Fn::Join:
        - ""
        - - "https://"
          - Ref: RestApi
          - Fn::Sub: ".execute-api.${AWS::Region}.amazonaws.com/dev"
